public class DateTimeMethodsDemo9 {
    public boolean leapYearCheck(date dt){
        integer dtYear = dt.year();
        boolean lp = date.isLeapYear(dtYear);
        return lp;
    }

    public integer add(integer num1, integer num2){
        integer name = num1 + num2;
        return name;
    }

    
    public integer add(integer num1, integer num2, integer num3){
        integer sum = num1 + num2 + num3;
        return sum;
    }
}
