/*car carObj1=new car();
carObj1.switchOn();*/
//1.save
//2.execute

//for classes
//1.save
//2. deploy

// i i am changing something here
// now i want to save this to org
//
car bm = new Car();
bm.carColor = 'Black';
bm.switchOn();
system.debug(bm);

car lm = new Car();
lm.carColor = 'red';
lm.switchOn();
//lm.maxSpeedKmPerHr = 100;
system.debug(lm);
car vm=new Car();
vm.carColor='White';
vm.carName='Polo';
vm.switchOn();
System.debug(vm);